# Name for the experiment (optional)
project_name: ""

# Path to the genome/transcriptome fasta file to align on (required)
fna: ""

# Path to the GFF annotation file (required)
gff: ""

# Path to the GFF annotation mapping file from orftrack (required)
gff_intergenic: ""

# Path of the directory containing your .fastq.gz file(s) (required)
path_to_fastq: ""

# set base directory location for orfribo outputs (optional - default='./orfribo_%datetime')
out_base: ""

# Fasta file with sequences you don't want to consider. (required) - @TODO: not working with empty file, either make it required or add condition in snakefile
fasta_outRNA: ""

# Are the sequencing adapters already removed in fastq files ? 'yes' or 'no'
already_trimmed: ""

# Adapter sequence (Example sequence for Illumina TruSeq™ single or CD index : "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA")
# Put "" if unknown, RiboDoc_BAM2Reads will try to find it for you
adapt_sequence: ""

# Minimum read length kept for ribosome profiling
readsLength_min: 25

# Maximum read length kept for ribosome profiling
readsLength_max: 35


# Elements to select during counting
gff_cds_feature: "CDS"

# Attribute containing the names of the genes in gff
gff_name_attribute: "Name"


# Minimum mean of in-frame reads in coding region to select specific read lengths
orfstats_mean_threshold: 70

# Minimum median of in-frame reads in coding region to select specific read lengths
orfstats_median_threshold: 70

# List of features to look for in the intergenic gff of the genome
final_counts: "nc_intergenic"

# Maximum allowed RAM to use (Mb)
mem_mb: 2000

# Number of maximum thread to use
threads: 3