site_name: ORFmine Documentation
nav:
    - Home: index.md
    - ORFmine:
      - Installation: orfmine_installation.md
      - Quick start: orfmine_quickstart.md
      - Citations: orfmine_citations.md
    - ORFtrack:
      - ORFtrack presentation:
        - Aims and general description: orftrack_description.md
        - ORF definition: orftrack_orfdef.md
        - ORF annotation: orftrack_annotation.md
        - Overlap definition: orftrack_overlap.md
        - ORF extraction: orftrack_orf_extraction.md
      - Usage:
        - Inputs: orftrack_input.md
        - ORF annotation with ORFtrack: orftrack_run.md
        - ORF extraction with ORFget: orfget_run.md
      - Parameters:
        - ORFtrack parameters: orftrack_param.md
        - ORFget parameters: orfget_param.md
    - ORFold:
      - ORFold presentation:
        - Objective: Objective_orfold.md
        - How it works?: How_it_works_orfold.md
      - Usage:
        - Basic run ORFold: Run_orfold.md
        - Plots with ORFplot: Plot_orfold.md
        - Advanced run ORFold: Run_orfold_advanced.md
      - Parameters:
        - ORFold parameters: parameters_orfold.md
        - ORFplot parameters: parameters_orfplot.md
    - ORFribo:
      - ORFribo presentation: 
        - Objectives: orfribo_objectives.md
        - How it works: How_it_works_orfribo.md
      - Usage:
        - Inputs: orfribo_inputs.md
        - ORFribo configuration: orfribo_configuration.md
        - Basic run ORFribo: orfribo_run.md
        - Advanced run ORFribo: orfribo_advanced.md
        - Outputs: orfribo_outputs.md
    - ORFdate:
      - ORFdate presentation:
        - Objectives: orfdate_objectives.md
        - How it works: How_it_works_orfdate.md
      - Usage:
        - Inputs: orfdate_inputs.md
        - Run: orfdate_run.md
        - Outputs: orfdate_outputs.md
        - Parameters: orfdate_parameters.md
     
theme: readthedocs
markdown_extensions:
    - footnotes
    - attr_list
    - toc:
        permalink: "#"
use_directory_urls: false
extra_css:
    - css/extra.css
extra_javascript:
    - js/extra.js
