site_name: ORFmine Documentation
nav:
    - Home: index.md
    - ORFmine:
      - Installation: orfmine_installation.md
      - Quick start: orfmine_quickstart.md
      - Citations: orfmine_citations.md
    - ORFmap:
      - ORFMap presentation:
        - Aims and general description: orfmap_description.md
        - ORF definition: orfmap_orfdef.md
        - ORF annotation: orfmap_annotation.md
        - Overlap definition: orfmap_overlap.md
        - ORF extraction: orfmap_orf_extraction.md
      - Usage:
        - Inputs: orfmap_input.md
        - ORF annotation with ORFmap: orfmap_run.md
        - ORF extraction with ORFget: orfget_run.md
      - Parameters:
        - ORFmap parameters: orfmap_param.md
        - ORFget parameters: orfget_param.md
    - ORFold:
      - ORFold presentation:
        - Objective: Objective_orfold.md
        - How it works?: How_it_works_orfold.md
      - Usage:
        - Basic run ORFold: Run_orfold.md
        - Plots with ORFplot: Plot_orfold.md
        - Advanced run ORFold: Run_orfold_advanced.md
      - Parameters:
        - ORFold parameters: parameters_orfold.md
        - ORFplot parameters: parameters_orfplot.md
theme: readthedocs
markdown_extensions:
    - footnotes
    - attr_list
    - toc:
        permalink: "#"
use_directory_urls: false
#extra_css:
#    - css/extra.css
